name: Delete Branch after Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    permissions:
      contents: write
    
    steps:
      - name: Delete branch
        run: |
          gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}